<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="4" hostname="Junior" name="be.iesca.colcinetFlights.tests.TestNG_Integration" tests="5" failures="1" timestamp="16 mai 2018 02:24:13 GMT" time="0.025" errors="0">
  <testcase name="testListerParNomEtPrenom" time="0.000" classname="be.iesca.colcinetFlights.tests.TestNG_Integration">
    <skipped/>
  </testcase> <!-- testListerParNomEtPrenom -->
  <testcase name="testAjouter" time="0.025" classname="be.iesca.colcinetFlights.tests.TestNG_Integration">
    <failure type="java.lang.AssertionError" message="">
      <![CDATA[java.lang.AssertionError: 
at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:33)
at be.iesca.colcinetFlights.tests.TestNG_Integration.testAjouter(TestNG_Integration.java:67)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testAjouter -->
  <testcase name="testListerParSolde" time="0.000" classname="be.iesca.colcinetFlights.tests.TestNG_Integration">
    <skipped/>
  </testcase> <!-- testListerParSolde -->
  <testcase name="testModifier" time="0.000" classname="be.iesca.colcinetFlights.tests.TestNG_Integration">
    <skipped/>
  </testcase> <!-- testModifier -->
  <testcase name="testRechercher" time="0.000" classname="be.iesca.colcinetFlights.tests.TestNG_Integration">
    <skipped/>
  </testcase> <!-- testRechercher -->
</testsuite> <!-- be.iesca.colcinetFlights.tests.TestNG_Integration -->
